### ISSUE TITLE
Formula `vdirsyncer` has not implemented #plist, #service or installed a locatable service file

### ISSUE THREAD

**Issue by vaboro** [pimutils/vdirsyncer#977]
Whenever I run

`brew services start vdirsyncer`

I get

`Error: Formula 'vdirsyncer' has not implemented #plist, #service or installed a locatable service file`

I have Homebrew 3.4.6-46-g1137386 and install vdirsyncer, version 0.18.0

<details>
  <summary>This is what's in the Cellar after install</summary>

**server:~ ladmin$ ls -la /usr/local/Cellar/vdirsyncer/0.18.0/
total 88
drwxr-xr-x  11 ladmin  admin    374 12 apr 18:35 .
drwxr-xr-x   3 ladmin  admin    102 12 apr 18:34 ..
drwxr-xr-x   3 ladmin  admin    102 12 apr 18:35 .brew
-rw-r--r--   1 ladmin  staff    490 11 apr 19:02 AUTHORS.rst
-rw-r--r--   1 ladmin  staff  20715 12 apr 18:34 CHANGELOG.rst
-rw-r--r--   1 ladmin  admin   1759 12 apr 18:35 INSTALL_RECEIPT.json
-rw-r--r--   1 ladmin  staff   1594 11 apr 19:02 LICENSE
-rw-r--r--   1 ladmin  staff   2213 12 apr 18:34 README.rst
drwxr-xr-x   3 ladmin  admin    102 12 apr 18:35 bin
drwxr-xr-x   6 ladmin  admin    204 12 apr 18:34 libexec
-rw-r--r--   1 ladmin  staff   1625 12 apr 18:35 vdirsyncer.plist**
</details>

Everything worked fine with vdirsyncer, version 16.8.0 with config file located at ~/.config/vdirsyncer/config
I tried to checkout vdirsyncer, version 16.8.0 from homebrew-core but then during installation I get:

`Error: vdirsyncer: undefined method 'cellar' for #<BottleSpecification:0x00007f868b143318>`

Looking for ways to resolve the issue with vdirsyncer, version 0.18.0.

**Comment by WhyNotHugo** [comment]
I suggest also opening an issue on the homebrew side.

I do see a `plist` file, so I've no idea what this error means.

**Comment by vaboro** [comment]
I've [opened](https://github.com/Homebrew/discussions/discussions/3176#discussion-4005391) an issue on the homebrew side and I think a solution may be as follows:

1. The `<key>Label</key>` should be `<string>homebrew.mxcl.vdirsyncer</string>`. I think line 16 in contrib/vdirsyncer.plist should be changed to `<string>@@LABEL@@</string>`. Then in homebrew-core/Formula/vdirsyncer.rb the `install` method should be updated with the line `s.gsub! "@@LABEL@@", plist_name` within `inreplace` block
2. The `post_install` method in homebrew-core/Formula/vdirsyncer.rb should be updated with the line `system "mv", prefix/"vdirsyncer.plist", plist_path`

After I implemented these changes the vdirsyncer service started to work again.

**Comment by vaboro** [comment]
@bernhardreiter Thank you for the homebrew merge!
